// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "exec")]
extern "C" {
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(command: &str) -> PromiseWithChild;
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_2(command: &str, options: &JsValue) -> PromiseWithChild;
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_3(command: &str, options: &JsValue) -> PromiseWithChild;
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_4(command: &str, options: &ExecOptions) -> PromiseWithChild;
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_5(command: &str, options: &JsValue) -> PromiseWithChild;
}
