// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl Address {
    pub fn new() -> Address {
        JsCast::unchecked_into(Object::new())
    }
}
impl Cluster {
    pub fn new() -> Cluster {
        JsCast::unchecked_into(Object::new())
    }
}
impl ClusterSettings {
    pub fn new() -> ClusterSettings {
        JsCast::unchecked_into(Object::new())
    }
}
impl Worker {
    pub fn new() -> Worker {
        JsCast::unchecked_into(Object::new())
    }
}
impl AsRef<EventEmitter> for Cluster {
    fn as_ref(&self) -> &EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<Cluster> for EventEmitter {
    fn from(child: Cluster) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<EventEmitter> for Worker {
    fn as_ref(&self) -> &EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<Worker> for EventEmitter {
    fn from(child: Worker) -> Self {
        JsCast::unchecked_into(child)
    }
}
