// generated by ts2rs 0.2.0
// https://ts2rs.ctaggart.com/

impl Address {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl Cluster {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl ClusterSettings {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl Worker {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl AsRef<node_js::EventEmitter> for Cluster {
    fn as_ref(&self) -> &node_js::EventEmitter {
        self.unchecked_ref()
    }
}
impl From<Cluster> for node_js::EventEmitter {
    fn from(child: Cluster) -> Self {
        child.unchecked_into()
    }
}
impl Cluster {
    pub fn to_node_js_event_emitter(self) -> node_js::EventEmitter {
        self.unchecked_into()
    }
    pub fn as_node_js_event_emitter(&self) -> &node_js::EventEmitter {
        self.unchecked_ref()
    }
}
impl AsRef<node_js::EventEmitter> for Worker {
    fn as_ref(&self) -> &node_js::EventEmitter {
        self.unchecked_ref()
    }
}
impl From<Worker> for node_js::EventEmitter {
    fn from(child: Worker) -> Self {
        child.unchecked_into()
    }
}
impl Worker {
    pub fn to_node_js_event_emitter(self) -> node_js::EventEmitter {
        self.unchecked_into()
    }
    pub fn as_node_js_event_emitter(&self) -> &node_js::EventEmitter {
        self.unchecked_ref()
    }
}
