// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "chown")]
extern "C" {
    #[doc = "Asynchronous chown(2) - Change ownership of a file."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(path: &crate::fs::PathLike, uid: f64, gid: f64) -> Promise;
}
