// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "copyFile")]
extern "C" {
    #[doc = "Asynchronously copies src to dest. By default, dest is overwritten if it already exists."]
    #[doc = "No arguments other than a possible exception are given to the callback function."]
    #[doc = "Node.js makes no guarantees about the atomicity of the copy operation."]
    #[doc = "If an error occurs after the destination file has been opened for writing, Node.js will attempt"]
    #[doc = "to remove the destination."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(src: &PathLike, dst: &PathLike, flags: Option<f64>) -> Promise;
}
