// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "fsync")]
extern "C" {
    #[doc = "Asynchronous fsync(2) - synchronize a file's in-core state with the underlying storage device."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(fd: f64) -> Promise;
}
