// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "realpath")]
extern "C" {
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(path: &crate::fs::PathLike, options: &JsValue) -> Promise;
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_2(path: &crate::fs::PathLike, options: &JsValue) -> Promise;
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous realpath(3) - return the canonicalized absolute pathname."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_3(path: &crate::fs::PathLike, options: &JsValue) -> Promise;
    #[wasm_bindgen()]
    pub fn native(path: &crate::fs::PathLike, options: &JsValue, callback: &JsValue);
    # [ wasm_bindgen ( js_name = native ) ]
    pub fn native2(path: &crate::fs::PathLike, options: &JsValue, callback: &JsValue);
    # [ wasm_bindgen ( js_name = native ) ]
    pub fn native3(path: &crate::fs::PathLike, options: &JsValue, callback: &JsValue);
    # [ wasm_bindgen ( js_name = native ) ]
    pub fn native4(path: &crate::fs::PathLike, callback: &JsValue);
}
