// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "readlink")]
extern "C" {
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(path: &PathLike, options: &JsValue) -> Promise;
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_2(path: &PathLike, options: &JsValue) -> Promise;
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    #[doc = ""]
    #[doc = ""]
    #[doc = "Asynchronous readlink(2) - read value of a symbolic link."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_3(path: &PathLike, options: &JsValue) -> Promise;
}
