// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "symlink")]
extern "C" {
    #[doc = "Asynchronous symlink(2) - Create a new symbolic link to an existing file."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(target: &PathLike, path: &PathLike, type_: &JsValue) -> Promise;
    pub type Type;
}
