// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "stat")]
extern "C" {
    #[doc = "Asynchronous stat(2) - Get file status."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(path: &PathLike) -> Promise;
    #[doc = "Asynchronous stat(2) - Get file status."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_2(path: &PathLike, options: &BigIntOptions) -> Promise;
    #[doc = "Asynchronous stat(2) - Get file status."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify_3(path: &PathLike, options: &StatOptions) -> Promise;
}
