// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "truncate")]
extern "C" {
    #[doc = "Asynchronous truncate(2) - Truncate a file to a specified length."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(path: &PathLike, len: &JsValue) -> Promise;
}
