// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "utimes")]
extern "C" {
    #[doc = "Asynchronously change file timestamps of the file referenced by the supplied path."]
    # [ wasm_bindgen ( js_name = __promisify__ ) ]
    pub fn promisify(path: &crate::fs::PathLike, atime: &JsValue, mtime: &JsValue) -> Promise;
}
