// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl Agent {
    pub fn new() -> Agent {
        JsCast::unchecked_into(Object::new())
    }
}
impl AgentOptions {
    pub fn new() -> AgentOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl ClientRequest {
    pub fn new() -> ClientRequest {
        JsCast::unchecked_into(Object::new())
    }
}
impl ClientRequestArgs {
    pub fn new() -> ClientRequestArgs {
        JsCast::unchecked_into(Object::new())
    }
}
impl IncomingHttpHeaders {
    pub fn new() -> IncomingHttpHeaders {
        JsCast::unchecked_into(Object::new())
    }
}
impl IncomingMessage {
    pub fn new() -> IncomingMessage {
        JsCast::unchecked_into(Object::new())
    }
}
impl InformationEvent {
    pub fn new() -> InformationEvent {
        JsCast::unchecked_into(Object::new())
    }
}
impl OutgoingHttpHeaders {
    pub fn new() -> OutgoingHttpHeaders {
        JsCast::unchecked_into(Object::new())
    }
}
impl OutgoingMessage {
    pub fn new() -> OutgoingMessage {
        JsCast::unchecked_into(Object::new())
    }
}
impl RequestOptions {
    pub fn new() -> RequestOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl Server {
    pub fn new() -> Server {
        JsCast::unchecked_into(Object::new())
    }
}
impl ServerOptions {
    pub fn new() -> ServerOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl ServerResponse {
    pub fn new() -> ServerResponse {
        JsCast::unchecked_into(Object::new())
    }
}
impl AsRef<EventEmitter> for ClientRequest {
    fn as_ref(&self) -> &EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<ClientRequest> for EventEmitter {
    fn from(child: ClientRequest) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<OutgoingMessage> for ClientRequest {
    fn as_ref(&self) -> &OutgoingMessage {
        JsCast::unchecked_ref(self)
    }
}
impl From<ClientRequest> for OutgoingMessage {
    fn from(child: ClientRequest) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<Stream> for ClientRequest {
    fn as_ref(&self) -> &Stream {
        JsCast::unchecked_ref(self)
    }
}
impl From<ClientRequest> for Stream {
    fn from(child: ClientRequest) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<Writable> for ClientRequest {
    fn as_ref(&self) -> &Writable {
        JsCast::unchecked_ref(self)
    }
}
impl From<ClientRequest> for Writable {
    fn from(child: ClientRequest) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<WritableStream> for ClientRequest {
    fn as_ref(&self) -> &WritableStream {
        JsCast::unchecked_ref(self)
    }
}
impl From<ClientRequest> for WritableStream {
    fn from(child: ClientRequest) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<EventEmitter> for IncomingMessage {
    fn as_ref(&self) -> &EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<IncomingMessage> for EventEmitter {
    fn from(child: IncomingMessage) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<Readable> for IncomingMessage {
    fn as_ref(&self) -> &Readable {
        JsCast::unchecked_ref(self)
    }
}
impl From<IncomingMessage> for Readable {
    fn from(child: IncomingMessage) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<ReadableStream> for IncomingMessage {
    fn as_ref(&self) -> &ReadableStream {
        JsCast::unchecked_ref(self)
    }
}
impl From<IncomingMessage> for ReadableStream {
    fn from(child: IncomingMessage) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<Stream> for IncomingMessage {
    fn as_ref(&self) -> &Stream {
        JsCast::unchecked_ref(self)
    }
}
impl From<IncomingMessage> for Stream {
    fn from(child: IncomingMessage) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<EventEmitter> for OutgoingMessage {
    fn as_ref(&self) -> &EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<OutgoingMessage> for EventEmitter {
    fn from(child: OutgoingMessage) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<Stream> for OutgoingMessage {
    fn as_ref(&self) -> &Stream {
        JsCast::unchecked_ref(self)
    }
}
impl From<OutgoingMessage> for Stream {
    fn from(child: OutgoingMessage) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<Writable> for OutgoingMessage {
    fn as_ref(&self) -> &Writable {
        JsCast::unchecked_ref(self)
    }
}
impl From<OutgoingMessage> for Writable {
    fn from(child: OutgoingMessage) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<WritableStream> for OutgoingMessage {
    fn as_ref(&self) -> &WritableStream {
        JsCast::unchecked_ref(self)
    }
}
impl From<OutgoingMessage> for WritableStream {
    fn from(child: OutgoingMessage) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<ClientRequestArgs> for RequestOptions {
    fn as_ref(&self) -> &ClientRequestArgs {
        JsCast::unchecked_ref(self)
    }
}
impl From<RequestOptions> for ClientRequestArgs {
    fn from(child: RequestOptions) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<NetServer> for Server {
    fn as_ref(&self) -> &NetServer {
        JsCast::unchecked_ref(self)
    }
}
impl From<Server> for NetServer {
    fn from(child: Server) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<EventEmitter> for ServerResponse {
    fn as_ref(&self) -> &EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<ServerResponse> for EventEmitter {
    fn from(child: ServerResponse) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<OutgoingMessage> for ServerResponse {
    fn as_ref(&self) -> &OutgoingMessage {
        JsCast::unchecked_ref(self)
    }
}
impl From<ServerResponse> for OutgoingMessage {
    fn from(child: ServerResponse) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<Stream> for ServerResponse {
    fn as_ref(&self) -> &Stream {
        JsCast::unchecked_ref(self)
    }
}
impl From<ServerResponse> for Stream {
    fn from(child: ServerResponse) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<Writable> for ServerResponse {
    fn as_ref(&self) -> &Writable {
        JsCast::unchecked_ref(self)
    }
}
impl From<ServerResponse> for Writable {
    fn from(child: ServerResponse) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<WritableStream> for ServerResponse {
    fn as_ref(&self) -> &WritableStream {
        JsCast::unchecked_ref(self)
    }
}
impl From<ServerResponse> for WritableStream {
    fn from(child: ServerResponse) -> Self {
        JsCast::unchecked_into(child)
    }
}
