// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl InspectorNotification {
    pub fn new() -> InspectorNotification {
        JsCast::unchecked_into(Object::new())
    }
}
impl Session {
    pub fn new() -> Session {
        JsCast::unchecked_into(Object::new())
    }
}
impl AsRef<crate::events::EventEmitter> for Session {
    fn as_ref(&self) -> &crate::events::EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<Session> for crate::events::EventEmitter {
    fn from(child: Session) -> Self {
        JsCast::unchecked_into(child)
    }
}
