// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl ConsoleMessage {
    pub fn new() -> ConsoleMessage {
        JsCast::unchecked_into(Object::new())
    }
}
impl MessageAddedEventDataType {
    pub fn new() -> MessageAddedEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
