// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl AttachedToWorkerEventDataType {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl DetachParameterType {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl DetachedFromWorkerEventDataType {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl EnableParameterType {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl ReceivedMessageFromWorkerEventDataType {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl SendMessageToWorkerParameterType {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
impl WorkerInfo {
    pub fn new() -> Self {
        Object::new().unchecked_into()
    }
}
