// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl BreakLocation {
    pub fn new() -> BreakLocation {
        JsCast::unchecked_into(Object::new())
    }
}
impl BreakpointResolvedEventDataType {
    pub fn new() -> BreakpointResolvedEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl CallFrame {
    pub fn new() -> CallFrame {
        JsCast::unchecked_into(Object::new())
    }
}
impl ContinueToLocationParameterType {
    pub fn new() -> ContinueToLocationParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl EnableReturnType {
    pub fn new() -> EnableReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl EvaluateOnCallFrameParameterType {
    pub fn new() -> EvaluateOnCallFrameParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl EvaluateOnCallFrameReturnType {
    pub fn new() -> EvaluateOnCallFrameReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl GetPossibleBreakpointsParameterType {
    pub fn new() -> GetPossibleBreakpointsParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl GetPossibleBreakpointsReturnType {
    pub fn new() -> GetPossibleBreakpointsReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl GetScriptSourceParameterType {
    pub fn new() -> GetScriptSourceParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl GetScriptSourceReturnType {
    pub fn new() -> GetScriptSourceReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl GetStackTraceParameterType {
    pub fn new() -> GetStackTraceParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl GetStackTraceReturnType {
    pub fn new() -> GetStackTraceReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl Location {
    pub fn new() -> Location {
        JsCast::unchecked_into(Object::new())
    }
}
impl PauseOnAsyncCallParameterType {
    pub fn new() -> PauseOnAsyncCallParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl PausedEventDataType {
    pub fn new() -> PausedEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl RemoveBreakpointParameterType {
    pub fn new() -> RemoveBreakpointParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl RestartFrameParameterType {
    pub fn new() -> RestartFrameParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl RestartFrameReturnType {
    pub fn new() -> RestartFrameReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl Scope {
    pub fn new() -> Scope {
        JsCast::unchecked_into(Object::new())
    }
}
impl ScriptFailedToParseEventDataType {
    pub fn new() -> ScriptFailedToParseEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl ScriptParsedEventDataType {
    pub fn new() -> ScriptParsedEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl ScriptPosition {
    pub fn new() -> ScriptPosition {
        JsCast::unchecked_into(Object::new())
    }
}
impl SearchInContentParameterType {
    pub fn new() -> SearchInContentParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SearchInContentReturnType {
    pub fn new() -> SearchInContentReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SearchMatch {
    pub fn new() -> SearchMatch {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetAsyncCallStackDepthParameterType {
    pub fn new() -> SetAsyncCallStackDepthParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetBlackboxPatternsParameterType {
    pub fn new() -> SetBlackboxPatternsParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetBlackboxedRangesParameterType {
    pub fn new() -> SetBlackboxedRangesParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetBreakpointByUrlParameterType {
    pub fn new() -> SetBreakpointByUrlParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetBreakpointByUrlReturnType {
    pub fn new() -> SetBreakpointByUrlReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetBreakpointParameterType {
    pub fn new() -> SetBreakpointParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetBreakpointReturnType {
    pub fn new() -> SetBreakpointReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetBreakpointsActiveParameterType {
    pub fn new() -> SetBreakpointsActiveParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetPauseOnExceptionsParameterType {
    pub fn new() -> SetPauseOnExceptionsParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetReturnValueParameterType {
    pub fn new() -> SetReturnValueParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetScriptSourceParameterType {
    pub fn new() -> SetScriptSourceParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetScriptSourceReturnType {
    pub fn new() -> SetScriptSourceReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetSkipAllPausesParameterType {
    pub fn new() -> SetSkipAllPausesParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetVariableValueParameterType {
    pub fn new() -> SetVariableValueParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl StepIntoParameterType {
    pub fn new() -> StepIntoParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
