// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl ConsoleProfileFinishedEventDataType {
    pub fn new() -> ConsoleProfileFinishedEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl ConsoleProfileStartedEventDataType {
    pub fn new() -> ConsoleProfileStartedEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl CoverageRange {
    pub fn new() -> CoverageRange {
        JsCast::unchecked_into(Object::new())
    }
}
impl FunctionCoverage {
    pub fn new() -> FunctionCoverage {
        JsCast::unchecked_into(Object::new())
    }
}
impl GetBestEffortCoverageReturnType {
    pub fn new() -> GetBestEffortCoverageReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl PositionTickInfo {
    pub fn new() -> PositionTickInfo {
        JsCast::unchecked_into(Object::new())
    }
}
impl Profile {
    pub fn new() -> Profile {
        JsCast::unchecked_into(Object::new())
    }
}
impl ProfileNode {
    pub fn new() -> ProfileNode {
        JsCast::unchecked_into(Object::new())
    }
}
impl ScriptCoverage {
    pub fn new() -> ScriptCoverage {
        JsCast::unchecked_into(Object::new())
    }
}
impl ScriptTypeProfile {
    pub fn new() -> ScriptTypeProfile {
        JsCast::unchecked_into(Object::new())
    }
}
impl SetSamplingIntervalParameterType {
    pub fn new() -> SetSamplingIntervalParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl StartPreciseCoverageParameterType {
    pub fn new() -> StartPreciseCoverageParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl StopReturnType {
    pub fn new() -> StopReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl TakePreciseCoverageReturnType {
    pub fn new() -> TakePreciseCoverageReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl TakeTypeProfileReturnType {
    pub fn new() -> TakeTypeProfileReturnType {
        JsCast::unchecked_into(Object::new())
    }
}
impl TypeObject {
    pub fn new() -> TypeObject {
        JsCast::unchecked_into(Object::new())
    }
}
impl TypeProfileEntry {
    pub fn new() -> TypeProfileEntry {
        JsCast::unchecked_into(Object::new())
    }
}
