// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl AttachedToWorkerEventDataType {
    pub fn new() -> AttachedToWorkerEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl DetachParameterType {
    pub fn new() -> DetachParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl DetachedFromWorkerEventDataType {
    pub fn new() -> DetachedFromWorkerEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl EnableParameterType {
    pub fn new() -> EnableParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl ReceivedMessageFromWorkerEventDataType {
    pub fn new() -> ReceivedMessageFromWorkerEventDataType {
        JsCast::unchecked_into(Object::new())
    }
}
impl SendMessageToWorkerParameterType {
    pub fn new() -> SendMessageToWorkerParameterType {
        JsCast::unchecked_into(Object::new())
    }
}
impl WorkerInfo {
    pub fn new() -> WorkerInfo {
        JsCast::unchecked_into(Object::new())
    }
}
