// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

#[wasm_bindgen(module = "perf_hooks")]
extern "C" {
    pub static NODE_PERFORMANCE_GC_MAJOR: String;
    pub static NODE_PERFORMANCE_GC_MINOR: String;
    pub static NODE_PERFORMANCE_GC_INCREMENTAL: String;
    pub static NODE_PERFORMANCE_GC_WEAKCB: String;
}
