// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl EventLoopDelayMonitor {
    pub fn new() -> EventLoopDelayMonitor {
        JsCast::unchecked_into(Object::new())
    }
}
impl EventLoopMonitorOptions {
    pub fn new() -> EventLoopMonitorOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl Performance {
    pub fn new() -> Performance {
        JsCast::unchecked_into(Object::new())
    }
}
impl PerformanceEntry {
    pub fn new() -> PerformanceEntry {
        JsCast::unchecked_into(Object::new())
    }
}
impl PerformanceNodeTiming {
    pub fn new() -> PerformanceNodeTiming {
        JsCast::unchecked_into(Object::new())
    }
}
impl PerformanceObserver {
    pub fn new() -> PerformanceObserver {
        JsCast::unchecked_into(Object::new())
    }
}
impl PerformanceObserverEntryList {
    pub fn new() -> PerformanceObserverEntryList {
        JsCast::unchecked_into(Object::new())
    }
}
impl AsRef<PerformanceEntry> for PerformanceNodeTiming {
    fn as_ref(&self) -> &PerformanceEntry {
        JsCast::unchecked_ref(self)
    }
}
impl From<PerformanceNodeTiming> for PerformanceEntry {
    fn from(child: PerformanceNodeTiming) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<crate::async_hooks::AsyncResource> for PerformanceObserver {
    fn as_ref(&self) -> &crate::async_hooks::AsyncResource {
        JsCast::unchecked_ref(self)
    }
}
impl From<PerformanceObserver> for crate::async_hooks::AsyncResource {
    fn from(child: PerformanceObserver) -> Self {
        JsCast::unchecked_into(child)
    }
}
