// generated by ts2rs 0.2.0
// https://ts2rs.ctaggart.com/

pub type Completer = Closure<dyn FnMut(String) -> CompleterResult>;
pub type AsyncCompleter = Closure<dyn FnMut(String, Function) -> JsValue>;
