// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl CreateTracingOptions {
    pub fn new() -> CreateTracingOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl Tracing {
    pub fn new() -> Tracing {
        JsCast::unchecked_into(Object::new())
    }
}
