// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl CustomPromisify {
    pub fn new() -> CustomPromisify {
        JsCast::unchecked_into(Object::new())
    }
}
impl EncodeIntoResult {
    pub fn new() -> EncodeIntoResult {
        JsCast::unchecked_into(Object::new())
    }
}
impl InspectOptions {
    pub fn new() -> InspectOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl TextDecoder {
    pub fn new() -> TextDecoder {
        JsCast::unchecked_into(Object::new())
    }
}
impl TextEncoder {
    pub fn new() -> TextEncoder {
        JsCast::unchecked_into(Object::new())
    }
}
impl AsRef<Function> for crate::util::CustomPromisify {
    fn as_ref(&self) -> &Function {
        JsCast::unchecked_ref(self)
    }
}
impl From<crate::util::CustomPromisify> for Function {
    fn from(child: crate::util::CustomPromisify) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<crate::node_js::InspectOptions> for crate::util::InspectOptions {
    fn as_ref(&self) -> &crate::node_js::InspectOptions {
        JsCast::unchecked_ref(self)
    }
}
impl From<crate::util::InspectOptions> for crate::node_js::InspectOptions {
    fn from(child: crate::util::InspectOptions) -> Self {
        JsCast::unchecked_into(child)
    }
}
