// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl BaseOptions {
    pub fn new() -> BaseOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl CompileFunctionOptions {
    pub fn new() -> CompileFunctionOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl Context {
    pub fn new() -> Context {
        JsCast::unchecked_into(Object::new())
    }
}
impl CreateContextOptions {
    pub fn new() -> CreateContextOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl RunningScriptOptions {
    pub fn new() -> RunningScriptOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl Script {
    pub fn new() -> Script {
        JsCast::unchecked_into(Object::new())
    }
}
impl ScriptOptions {
    pub fn new() -> ScriptOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl AsRef<BaseOptions> for CompileFunctionOptions {
    fn as_ref(&self) -> &BaseOptions {
        JsCast::unchecked_ref(self)
    }
}
impl From<CompileFunctionOptions> for BaseOptions {
    fn from(child: CompileFunctionOptions) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<BaseOptions> for RunningScriptOptions {
    fn as_ref(&self) -> &BaseOptions {
        JsCast::unchecked_ref(self)
    }
}
impl From<RunningScriptOptions> for BaseOptions {
    fn from(child: RunningScriptOptions) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<BaseOptions> for ScriptOptions {
    fn as_ref(&self) -> &BaseOptions {
        JsCast::unchecked_ref(self)
    }
}
impl From<ScriptOptions> for BaseOptions {
    fn from(child: ScriptOptions) -> Self {
        JsCast::unchecked_into(child)
    }
}
