// generated by ts2rs 0.1.4
// https://ts2rs.ctaggart.com/

impl MessageChannel {
    pub fn new() -> MessageChannel {
        JsCast::unchecked_into(Object::new())
    }
}
impl MessagePort {
    pub fn new() -> MessagePort {
        JsCast::unchecked_into(Object::new())
    }
}
impl Worker {
    pub fn new() -> Worker {
        JsCast::unchecked_into(Object::new())
    }
}
impl WorkerOptions {
    pub fn new() -> WorkerOptions {
        JsCast::unchecked_into(Object::new())
    }
}
impl AsRef<EventEmitter> for MessagePort {
    fn as_ref(&self) -> &EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<MessagePort> for EventEmitter {
    fn from(child: MessagePort) -> Self {
        JsCast::unchecked_into(child)
    }
}
impl AsRef<EventEmitter> for Worker {
    fn as_ref(&self) -> &EventEmitter {
        JsCast::unchecked_ref(self)
    }
}
impl From<Worker> for EventEmitter {
    fn from(child: Worker) -> Self {
        JsCast::unchecked_into(child)
    }
}
